### ISSUE TITLE
Typing breaks Python 2

### ISSUE THREAD

**Issue by ColdHeat** [pudo/banal#5]
By adding typing I think you just broke Python 2 compatibility.

```
In [1]: from banal import decode_path
  File "/Users/kchung/.virtualenvs/ctfd/lib/python2.7/site-packages/banal/lists.py", line 5
    def is_sequence(obj: Any) -> bool:
                       ^
SyntaxError: invalid syntax
```

**Comment by pudo** [comment]
Yes, that's why I tagged it as a major version break. If you want to continue the discontinued Python 2 version, just pin it to `< 1.0.0`.

**Comment by ColdHeat** [comment]
Yes but you pinned banal to above 0.4.1 in your normality project (https://github.com/pudo/normality/blob/master/setup.py#L34) which means old versions of that just randomly broke.

**Comment by pudo** [comment]
I apologise for causing you the need to pin this! Hope you're as excited as I am about upping the state of the Python ecosystem with new features like this in the long run :)
